const WORLD_NAME_DATA = {
    "compositions": {
        "1": "{Adjective} {Location} {Noun}",
        "2": "{Adjective} {Location} {Noun}",
        "3": "{Adjective} {Location} {Noun}",
        "4": "{Adjective} {Location} {Noun}",
        "5": "{Adjective} {Location}",
        "6": "{Adjective} {Location}",
        "7": "{Location} {Noun}",
        "8": "{Location} {Noun}"
    },
    "adjectives": {
		"Abandoned": "Заброшенный",
		"Abhorrent": "Омерзительный",
		"Abusive": "Жестокий",
		"Adorable": "Прелестный",
		"Adventurous": "Рискованный",
		"Ageless": "Нестареющий",
		"Aggravating": "Досадный",
		"Aggressive": "Агрессивный",
		"Agile": "Подвижный",
		"Agreeable": "Покладистый",
		"Alert": "Настороженный",
		"Alien": "Чужой",
		"Alive": "Живой",
		"Alleged": "Подозрительный",
		"Amethyst": "Аметист",
		"Amusing": "Забавный",
		"Ancient": "Древний",
		"Angelic": "Ангельский",
		"Angry": "Сердящий",
		"Annoyed": "Раздраженный",
		"Annoying": "Раздражающий",
		"Anxious": "Тревожный",
		"Archaic": "Устаревший",
		"Ardent": "Пылкий",
		"Arrogant": "Надменный",
		"Ashamed": "Пристыженный",
		"Attractive": "Привлекательный",
		"AuntBeckys": "Тетушкин",
		"Average": "Средний",
		"Awful": "Отвратительный",
		"Awkward": "Странный",
		"Babbling": "Журчащий",
		"Bad": "Плохой",
		"Bashful": "Стыдливый",
		"Beautiful": "Красивый",
		"Best": "Лучший",
		"Bewildered": "Озадаченный",
		"Bitter": "Горький",
		"Bizarre": "Необычный",
		"Black": "Черный",
		"Blackish": "Черноватый",
		"Bleeding": "Кровотечение",
		"Blistering": "Разъяренный",
		"Blocky": "Глыбистый",
		"Bloody": "Кровавый",
		"Blooming": "Цветущий",
		"Blue": "Синий",
		"Blushful": "Робкий",
		"Blushing": "Стыдливый",
		"Boorish": "Хамский",
		"Bored": "Скучающий",
		"Boundless": "Безграничный",
		"Brainy": "Мозговитый",
		"Brash": "Порывистый",
		"Brave": "Смелый",
		"Breakable": "Хрупкий",
		"Breakless": "Непрерывный",
		"Breathtaking": "Захватывающий дух",
		"Bright": "Яркий",
		"Brilliant": "Гениальный",
		"Broken": "Сломаный",
		"Brown": "Коричневый",
		"Brutal": "Зверский",
		"Budding": "Многообещающий",
		"Burning": "Ожог",
		"Busy": "Занятый",
		"Calm": "Спокойствие",
		"Canadian": "Канадский",
		"Careful": "Осторожный",
		"Cautious": "Осмотрительный",
		"Celestial": "Небесный",
		"Chads": "Сашин",
		"Charming": "Очаровательный",
		"Chartreuse": "Бледно-зеленый",
		"Cheap": "Дешевый",
		"Cheerful": "Неунывающий",
		"Clean": "Чистый",
		"Clear": "Очистить",
		"Clearable": "Обнуляемый",
		"Clever": "Умный",
		"Cleverish": "Умненький",
		"Cloudy": "Облачно",
		"Clumsy": "Неуклюжий",
		"Cold": "Холодный",
		"Colorful": "Цветастый",
		"Combative": "Боевой",
		"Comfortable": "Удобный",
		"Comical": "Забавный",
		"Common": "Распространенный",
		"Complacent": "Услужливый",
		"Compulsive": "Навязчивый",
		"Concerned": "Сосредоточенный",
		"Condemnable": "Заслуживающий осуждения",
		"Condemned": "Приговоренный",
		"Confident": "Самоуверенный",
		"Confusable": "Трудноразличимый",
		"Confused": "Запутанность",
		"Constant": "Постоянный",
		"Cooperative": "Приветливый",
		"Corrupted": "Испорченный",
		"Cosmic": "Космический",
		"Courageous": "Храбрый",
		"Cracked": "Треснутый",
		"Cranky": "Разваливающийся",
		"Crass": "Тупой",
		"Crazy": "Сумасшедший",
		"Creepy": "Противный",
		"Crowded": "Переполненный",
		"Crude": "Необработанный",
		"Cruel": "Жестокий",
		"Cuddly": "Аппетитный",
		"Curious": "Любопытный",
		"Cursed": "Проклятие",
		"Cute": "Забавный",
		"Daft": "Безрассудный",
		"Damaged": "Поврежденный",
		"Dangerous": "Опасный",
		"Dank": "Промозглый",
		"Dark": "Темный",
		"Daunting": "Обескураживающий",
		"Dead": "Мертвый",
		"Decaying": "Загнивающий",
		"Deceased": "Покойный",
		"Defeated": "Побежденный",
		"Defiant": "Непокорный",
		"Delightful": "Упоительный",
		"Demented": "Слабоумный",
		"Demonic": "Демонический",
		"Dense": "Густой",
		"Depressed": "Угнетенный",
		"Deranged": "Неуравновешенный",
		"Desolate": "Заброшенный",
		"Desperate": "Отчаявшийся",
		"Determined": "Непреклонный",
		"Devious": "Окольный",
		"Diamond": "Алмаз",
		"Different": "Необычный",
		"Difficult": "Сложный",
		"Dire": "Катастрофический",
		"Dirty": "Грязный",
		"Disappointing": "Досадный",
		"Discarded": "Забракованный",
		"Disgusting": "Отвратительный",
		"Disloyal": "Предательский",
		"Distant": "Отдаленный",
		"Distinct": "Отчетливый",
		"Distorted": "Искажение",
		"Distressing": "Неутешительный",
		"Disturbed": "Обеспокоенный",
		"Divine": "Божественный",
		"Dizzy": "Головокружительный",
		"Docile": "Покорный",
		"Doubtful": "Сомнительный",
		"Drab": "Монотонный",
		"Dreadful": "Ужасающий",
		"Dreamy": "Призрачный",
		"Dry": "Сухой",
		"Dubious": "Подозрительный",
		"Dull": "Тупой",
		"Dumb": "Немой",
		"Eager": "Жаждущий",
		"Easy": "Легкий",
		"Eerie": "Потусторонний",
		"Elated": "Окрыленный",
		"Elegant": "Элегантный",
		"Embarrassed": "Смущенный",
		"Embarrassing": "Затруднительный",
		"Emerald": "Изумруд",
		"Empty": "Пустой",
		"Enchanting": "Пленительный",
		"Encouraging": "Воодушевляющий",
		"Enduring": "Выносливый",
		"Energetic": "Энергичный",
		"Enthusiastic": "Увлеченный",
		"Envious": "Завидующий",
		"Erratic": "Блуждающий",
		"Eternal": "Вечный",
		"Euphoric": "Благодушный",
		"Everlasting": "Нескончаемый",
		"Evil": "Злой",
		"Exalted": "Возвышенный",
		"Excellent": "Отличный",
		"Excited": "Возбужденный",
		"Exiled": "Изгнанный",
		"Existential": "Экзистенциальный",
		"Exotic": "Экзотический",
		"Expensive": "Дорогой",
		"Extinct": "Потухший",
		"Extraordinary": "Поразительный",
		"Extravagant": "Экстравагантный",
		"Exuberant": "Обильный",
		"Fabulous": "Невероятный",
		"Fair": "Справедливый",
		"Faithful": "Правдивый",
		"Fallen": "Упавший",
		"Famous": "Знаменитый",
		"Fancy": "Узорчатый",
		"Fantastic": "Фантастический",
		"Far": "Дальний",
		"Faraway": "Отдаленный",
		"Fearful": "Боязливый",
		"Fearsome": "Устрашающий",
		"Fierce": "Свирепый",
		"Filthy": "Нечистый",
		"Fine": "Изысканный",
		"Firm": "Твердый",
		"Flaky": "Чешуйчатый",
		"Flaming": "Пламенеющий",
		"Flatulent": "Напыщенный",
		"Fluffy": "Пушистик",
		"Foolhardy": "Бесшабашный",
		"Foolish": "Вздорный",
		"Forceful": "Неистовый",
		"Foreign": "Заморский",
		"Forgiving": "Великодушный",
		"Forgotten": "Забытый",
		"Forsaken": "Заброшенный",
		"Foul": "Ненастный",
		"Fragile": "Уязвимый",
		"Frail": "Непрочный",
		"Frantic": "Исступленный",
		"Fresh": "Свежий",
		"Friendly": "Дружелюбный",
		"Frightened": "Напуганный",
		"Frightening": "Пугающий",
		"Funny": "Прикольный",
		"Furious": "Яростный",
		"Gangrenous": "Омертвелый",
		"Gentle": "Кроткий",
		"Gifted": "Одаренный",
		"Glamorous": "Эффектный",
		"Gleaming": "Сияющий",
		"Gleamless": "Несветящийся",
		"Gloomy": "Хмурый",
		"Glorious": "Славный",
		"Glowing": "Светящийся",
		"Godly": "Праведный",
		"Good": "Хороший",
		"Gorgeous": "Великолепный",
		"Graceful": "Грациозный",
		"Grand": "Величественный",
		"Grassy": "Травяной",
		"Gray": "Серый",
		"Greasy": "Замасленный",
		"Great": "Великий",
		"Greedy": "Жадный",
		"Green": "Зеленый",
		"Grieving": "Скорбящий",
		"Grizzly": "Седоватый",
		"Grotesque": "Неправдоподобный",
		"Grouchy": "Брюзгливый",
		"Growing": "Растущий",
		"Gruesome": "Шокирующий",
		"Grumpy": "Ворчливый",
		"Guilty": "Виноватый",
		"Gutless": "Бесхарактерный",
		"Hallowed": "Освященный",
		"Handsome": "Красивый",
		"Happy": "Счастливый",
		"Harsh": "Шероховатый",
		"Hateful": "Ненавистный",
		"Hazardous": "Рискованный",
		"Healthy": "Здоровый",
		"Heartless": "Бессердечный",
		"Heavenly": "Неземной",
		"Heinous": "Гнусный",
		"Helpful": "Услужливый",
		"Helpless": "Беспомощный",
		"Hesitant": "Колеблющийся",
		"Hidden": "Скрыто",
		"Hideous": "Отталкивающий",
		"Hilarious": "Уморительный",
		"Holy": "Святой",
		"Homeless": "Бездомный",
		"Homely": "Непритязательный",
		"Horrible": "Кошмарный",
		"Horrific": "Ужасающий",
		"Horrifying": "Шокирующий",
		"Hungry": "Голодный",
		"Hurt": "Раненый",
		"Hurtable": "Ранимый",
		"Hurtful": "Вредный",
		"Hyper": "Чрезмерный",
		"Hysterical": "Истеричный",
		"Ignorant": "Грубый",
		"Illicit": "Противоправный",
		"Illusive": "Иллюзорный",
		"Imaginary": "Выдуманный",
		"Immortal": "Нетленный",
		"Incompetent": "Несведущий",
		"Inconvenient": "Неподходящий",
		"Indecisive": "Неопределенный",
		"Indifferent": "Безразличный",
		"Inferior": "Нижний",
		"Infinite": "Бесконечный",
		"Insecure": "Небезопасный",
		"Insolent": "Высокомерный",
		"Intense": "Значительный",
		"Irresponsible": "Несознательный",
		"Irritating": "Раздражающий",
		"Isolated": "Изолированный",
		"Jade": "Нефритовый",
		"Jealous": "Ревнивый",
		"Jiggly": "Покачивающийся",
		"Jittery": "Нервозный",
		"Jolly": "Радостный",
		"Joyous": "Довольный",
		"Judgmental": "Осуждающий",
		"Karens": "Катин",
		"Keen": "Заточенный",
		"Kind": "Добрый",
		"Kooky": "Придурковатый",
		"Large": "Большой",
		"Lasting": "Устойчивый",
		"Lavish": "Щедрый",
		"Lazy": "Лентяйский",
		"Leafy": "Лиственный",
		"Legendary": "Легендарный",
		"Light": "Свет",
		"Lightful": "Светоносный",
		"Lime": "Известковый",
		"Littleknown": "Малоизвестный",
		"Lively": "Живой",
		"Lonely": "Одинокий",
		"Long": "Длинный",
		"Lost": "Потерянный",
		"Lousy": "Вшивый",
		"Lovely": "Прелестный",
		"Loyal": "Верный",
		"Lucky": "Счастливый",
		"Mad": "Сердитый",
		"Magical": "Волшебный",
		"Magnificent": "Великолепный",
		"Marvelous": "Изумительный",
		"Massive": "Массивный",
		"Menacing": "Грозный",
		"Merciless": "Беспощадный",
		"Mischievous": "Озорной",
		"Miserable": "Обездоленный",
		"Misty": "Туманчик",
		"Modern": "Современный",
		"Modular": "Модульный",
		"Moist": "Сырой",
		"Moldy": "Заплесневелый",
		"Mopey": "Депрессивный",
		"Motionless": "Неподвижный",
		"Mourning": "Плакучий",
		"Muddy": "Грязный",
		"Multitalented": "Одаренный",
		"Murderous": "Убийственный",
		"Murky": "Сумрачный",
		"Mushy": "Пористый",
		"Mysterious": "Таинственный",
		"Mythical": "Загадочный",
		"Naive": "Наивный",
		"Naked": "Обнаженный",
		"Nameless": "Безымянный",
		"Nasty": "Мерзкий",
		"Natural": "Естественный",
		"Naughty": "Капризный",
		"Nauseating": "Тошнотворный",
		"Navy": "Военно-морской",
		"Neglected": "Заброшенный",
		"Nervous": "Нервный",
		"New": "Новый",
		"Nice": "Милый",
		"Nimble": "Шустрый",
		"Nude": "Оголенный",
		"Nutty": "Ореховый",
		"Obedient": "Покорный",
		"Obnoxious": "Оскорбительный",
		"Obsessive": "Одержимый",
		"Obstructed": "Затемнение",
		"Obtuse": "Идиотский",
		"Odd": "Лишний",
		"Offended": "Оскорбленный",
		"Offensive": "Оскорбительный",
		"Old": "Старый",
		"OldFashioned": "Старомодный",
		"Olive": "Оливковый",
		"Open": "Открытый",
		"Optimistic": "Оптимистичный",
		"Outraged": "Возмущенный",
		"Outrageous": "Негодующий",
		"Outstanding": "Знаменитый",
		"Overcrowded": "Переполненный",
		"Overeasy": "Сверхлегкий",
		"Overjealous": "Слишком ревнивый",
		"Overjoyous": "Слишком веселый",
		"Overrun": "Переполненный",
		"Pale": "Бледный",
		"Panicky": "Панический",
		"Peaceful": "Мирный",
		"Perfect": "Совершенный",
		"Perilous": "Пагубный",
		"Perpetual": "Вечный",
		"Persistent": "Настойчивый",
		"Petrified": "Окаменелый",
		"Pine": "Сосновый",
		"Placid": "Безмятежный",
		"Plain": "Плоский",
		"Pleasant": "Приятный",
		"Pleasing": "Угодливый",
		"Pointy": "Заостренный",
		"Poised": "Уравновешенный",
		"Poison": "Ядовитый",
		"Poor": "Бедный",
		"Powerful": "Мощный",
		"Precious": "Ценный",
		"Prickly": "Тернистый",
		"Proud": "Гордый",
		"Purified": "Очищенный",
		"Putrid": "Гнилой",
		"Puzzled": "Растерянный",
		"Quaint": "Причудливый",
		"Quick": "Быстрый",
		"Quiet": "Тихий",
		"Quirky": "Чудаковатый",
		"Rancid": "Прогорклый",
		"Rank": "Пышный",
		"Raunchy": "Неопрятный",
		"Raw": "Сырой",
		"Real": "Настоящий",
		"Reckless": "Безрассудный",
		"Red's": "Петин",
		"Reeking": "Протухший",
		"Rejected": "Отклоненный",
		"Relentless": "Непреклонный",
		"Relievable": "Исправимый",
		"Relieved": "Облегченный",
		"Remote": "Удаленный",
		"Repugnant": "Отталкивающий",
		"Repulsive": "Отвратный",
		"Resentful": "Озлобленный",
		"Restful": "Спокойный",
		"Revolting": "Возмутительный",
		"Rich": "Богатый",
		"Ridiculous": "Смешной",
		"Risky": "Рискованный",
		"Rotten": "Тухлый",
		"Rotting": "Гниющий",
		"Royal": "Королевский",
		"Ruby": "Рубинчик",
		"Rude": "Оскорбительный",
		"Ruthless": "Безжалостный",
		"Sacred": "Священный",
		"Sad": "Печальный",
		"Sadistic": "Садистский",
		"Sage": "Мудрый",
		"Sallow": "Землистый",
		"Sapphire": "Сапфир",
		"Savage": "Дикий",
		"Scandalous": "Скандальный",
		"Scary": "Пугливый",
		"Searing": "Пронзительный",
		"Sedated": "Усыпленный",
		"Selfish": "Эгоистичный",
		"Senseless": "Бездыханный",
		"Sensitive": "Чувствительный",
		"Serene": "Безмятежный",
		"Serious": "Серьезный",
		"Shabby": "Поношенный",
		"Shameful": "Позорный",
		"Sharp": "Острый",
		"Shiny": "Блестящий",
		"Shocking": "Шокирующий",
		"Shoddy": "Некачественный",
		"Shy": "Застенчивый",
		"Significant": "Значительный",
		"Silenced": "Немота",
		"Silly": "Глупый",
		"Simple": "Простой",
		"Sleazy": "Тонкий",
		"Sleepy": "Сонный",
		"Slow": "Замедление",
		"Sluggish": "Медлительный",
		"Smelly": "Ароматный",
		"Smiling": "Улыбчивый",
		"Smoggy": "Затянутый смогом",
		"Smooth": "Гладкий",
		"Smouldering": "Тлеющий",
		"Solid": "Плотный",
		"Sore": "Болезненный",
		"Sour": "Кислый",
		"Sparkling": "Блестящий",
		"Spastic": "Спазматический",
		"Spiritual": "Духовный",
		"Splendid": "Блистательный",
		"Spoiled": "Испорченный",
		"Spooky": "Жуткий",
		"Spotless": "Незапятнанный",
		"Stable": "Устойчивый",
		"Stalwart": "Непоколебимый",
		"Staunch": "Крепкий",
		"Stiff": "Жесткий",
		"Still": "Неподвижный",
		"Stinky": "Вонь",
		"Stormy": "Штормовой",
		"Strange": "Странный",
		"Strong": "Прочный",
		"Stupid": "Глупый",
		"Subaverage": "Такой себе",
		"Successful": "Успешный",
		"Super": "Отличный",
		"Superb": "Великолепный",
		"Superior": "Превосходный",
		"Supreme": "Верховный",
		"Sweaty": "Потный",
		"Tainted": "Гниющий",
		"Talented": "Талантливый",
		"Tame": "Покорный",
		"Tasty": "Вкусный",
		"Teal": "Бирюзовый",
		"Tender": "Мягкий",
		"Tense": "Натянутый",
		"Terrible": "Ужасный",
		"Terrified": "Испуганный",
		"Thankful": "Благодарный",
		"Thanos": "Таноса",
		"Thick": "Толстый",
		"Thoughtful": "Задумчивый",
		"Thoughtless": "Бездумный",
		"Timeless": "Нетленный",
		"Tiny": "Маленький",
		"Tired": "Усталый",
		"Topaz": "Топазовый",
		"Tough": "Жесткий",
		"Tranquil": "Спокойный",
		"Trashy": "Скверный",
		"Tropical": "Тропический",
		"Troubled": "Беспокойный",
		"Trusting": "Доверчивый",
		"Ugliest": "Самый уродливый",
		"Ugly": "Уродливый",
		"Unbroken": "Несломанный",
		"Uncharming": "Расколдовывающий",
		"Uncharted": "Неисследованный",
		"Uncombative": "Небоевой",
		"Uncooperative": "Несговорчивый",
		"Undetermined": "Нерешительный",
		"Undiscovered": "Неоткрытый",
		"Undying": "Непрекращающийся",
		"Unending": "Бесконечный",
		"Unexplored": "Неисследованный",
		"Unhappy": "Невезучий",
		"Unhurt": "Невредимый",
		"Unhurting": "Безобидный",
		"Uninterested": "Незаинтересованный",
		"Unknown": "Неизвестный",
		"Unlawful": "Незаконный",
		"Unpleasant": "Неприятный",
		"Unreal": "Нереальный",
		"Unruly": "Непослушный",
		"Unsightly": "Неприглядный",
		"Unsure": "Ненадежный",
		"Untalented": "Бездарный",
		"Untamed": "Неукрощенный",
		"Unusual": "Непривычный",
		"Unwicked": "Незлобный",
		"Unworried": "Спокойный",
		"Upset": "Огорченный",
		"Upsetable": "Опрокидываемый",
		"Uptight": "Скованный",
		"Useless": "Бесполезный",
		"Vague": "Нечеткий",
		"Vain": "Тщетный",
		"Vast": "Обширный",
		"Vibrant": "Трепещущий",
		"Vicious": "Порочный",
		"Victorious": "Победоносный",
		"Vile": "Подлый",
		"Violent": "Жестокий",
		"Viridian": "Голубовато-зеленый",
		"Vivacious": "Бодрый",
		"Volatile": "Изменчивый",
		"Vulgar": "Вульгарный",
		"Wacky": "Юродивый",
		"Wandering": "Блуждающий",
		"Wary": "Осмотрительный",
		"Weak": "Слабый",
		"Weary": "Утомленный",
		"Weepy": "Плаксивый",
		"Weird": "Странный",
		"Wellamused": "Очень довольный",
		"Wellfrightened": "До смерти напуганный",
		"Wet": "Влага",
		"Wicked": "Безнравственный",
		"Wild": "Дикий",
		"Windy": "Ветренный",
		"Wishful": "Желаемый",
		"Withered": "Иссохший",
		"Witless": "Безмозглый",
		"Witty": "Шутливый",
		"Wonderful": "Удивительный",
		"Wondrous": "Диковинный",
		"Worried": "Обеспокоенный",
		"Worrisome": "Беспокоящий",
		"Wriggly": "Извивающийся",
		"Wrong": "Неправильный",
		"Yellow": "Желтый",
		"YOLO": "Одноразовый",
		"Zany": "Потешный",
		"Zealous": "Пылкий",
		"Vanilla": "Ванильный",
		"Sus": "Фальшивый",
		"Woke": "Проснувшийся",
		"Canceled": "Отменённый",
		"BobSaget": "Программный",
		"Fleek": "Шикарный",
		"Dope": "Активаторный",
		"Basic": "Основной",
		"Ghosted": "Рентгеновский",
		"Cringe": "Стыдный",
		"Ballin": "Налипающий",
		"Highkey": "Светлый",
		"Lowkey": "Тёмный",
		"Mathematical": "Математический",
		"Bloopy": "Булькающий",
		"Natchy": "Естественный",
		"SkronkedUp": "Брынькающий",
		"RentFree": "Бесплатный",
		"Extra": "Дополнительный",
		"Thirsty": "Алчущий",
		"Saucy": "Фривольный",
		"Big": "Крупный",
		"Smol": "Малый",
		"Glubbed Up": "Клокочущий",
		"Griefing": "Вредоносный",
		"Lagging": "Отстающий",
		"Aloof": "Замкнутый",
		"Itchy": "Зудящий",
		"Frisky": "Резвый",
		"Unacceptable": "Неприемлемый",
		"Lumpy": "Бугорчатый",
		"Flexing": "Гибкий",
		"Flat": "Равнинный",
		"Voluptuous": "Любовный",
		"Uncanny": "Зловещий",
		"Supernatural": "Сверхъестественный",
		"Vampiric": "Вампирический",
		"Degenerative": "Вырождающийся",
		"Posturing": "Позирующий",
		"Patronizing": "Снисходительный",
		"Subpar": "Подкачавший",
		"Disruptive": "Подрывной",
		"Baleful": "Гибельный",
		"Corpulent": "Мясистый",
		"Dapper": "Опрятный",
		"Draconian": "Драконовский",
		"Feckless": "Нерадивый",
		"Insidious": "Вероломный",
		"Luminous": "Лучезарный",
		"Noxious": "Тлетворный",
		"Tenacious": "Вязкий",
		"Verdant": "Незрелый",
		"Planking": "Обшивочный",
		"DeadMans": "Мертвецкий",
		"NonFungible": "Незаменимый",
		"Spicy": "Пряный",
		"Safe": "Безопасный",
		"Festering": "Терзающий",
		"Fetid": "Зловонный",
		"Seasick": "Страдающий",
		"Salty": "Солёный",
		"Fraudulent": "Мошеннический",
		"Hardcore": "Хардкорный",
		"Sticky": "Липкий",
		"Dripping": "Капающий",
		"Flowing": "Текущий",
		"Hot": "Горячий",
		"Infected": "Заражённый",
		"Bodacious": "Эпатажный",
		"Steaming": "Дымящийся",
		"Moonlit": "Лунный",
		"Partying": "Гулящий",
		"Feral": "Дикий",
		"Sandy": "Песчаный",
		"Hybrid": "Гибридный",
		"HappyLittle": "Улыбчатый",
		"Fortified": "Укреплённый",
		"EggFaced": "Яйцеголовый",
		"Silver": "Серебряный",
		"Unforgivable": "Непростительный",
		"Apple": "Яблочный",
		"Cooked": "Печёный",
		"Golden": "Золотой",
		"Prismatic": "Призматический",
		"Chicken": "Цыплячий",
		"Guides": "Направляющий",
		"Painters": "Художественный",
		"Goblin": "Гоблинский",
		"Traveling": "Путешествующий",
		"Skeleton": "Скелетный",
		"Undead": "Немёртвый",
		"Skeletrons": "Скелетронский",
		"Moon Lords": "Лордовский",
		"Solar": "Солнечный",
		"Magnetic": "Магнетический",
		"Corrupt": "Искажённый",
		"Round": "Круглый",
		"Senile": "Дряхлый",
		"Pink": "Розовый",
		"Red": "Красный",
		"Purple": "Пурпурный",
		"Orange": "Оранжевый",
		"Violet": "Фиолетовый",
		"Cyan": "Бирюзовый",
		"White": "Белый",
		"Amber": "Янтарный",
		"Marshmallow": "Зефирный",
		"Pumpkin": "Тыквенный",
		"Cherry": "Вишнёвый",
		"Lemon": "Лимонный",
		"Peach": "Персиковый",
		"Fertile": "Плодородный",
		"Fruitful": "Хлебный",
		"Lush": "Злачный",
		"Flowering": "Цветочный",
		"Lavender": "Лавандовый",
		"Unbreakable": "Небьющийся",
		"Devils": "Дьявольский",
		"Chippys": "Щербатый",
		"Lights": "Световой",
		"Nights": "Ночной"
	},
    "locations": {
		"Abode": "приют",
		"Abyss": "хаос",
		"Acres": "акр",
		"Afterworld": "могильник",
		"Alcove": "альков",
		"Alley": "проход",
		"Apogee": "апогей",
		"Arbor": "вал",
		"Archipelago": "архипелаг",
		"Area": "район",
		"Arena": "манеж",
		"Armpit": "глухой край",
		"Artwork": "шедевр",
		"Asylum": "приют",
		"Backcountry": "малонаселенный район",
		"Backwater": "застой",
		"Backwoods": "задворок",
		"Badlands": "пустырь",
		"Bank": "берег",
		"Barren": "буй",
		"Base": "поддон",
		"Basin": "резервуар",
		"Bastion": "бастион",
		"Bay": "залив",
		"Bayou": "ручей",
		"Beach": "пляж",
		"Bed": "Кровать",
		"Bedrock": "фундамент",
		"Beyond": "загробный мир",
		"Biosphere": "заповедник",
		"Bluff": "утес",
		"Bog": "торфяник",
		"Boondocks": "задворок",
		"Boonies": "Тьмутаракань",
		"Border": "предел",
		"Bottoms": "низ",
		"Boundary": "рубеж",
		"Breach": "пролом",
		"Brewery": "пивзавод",
		"Brook": "ручей",
		"Bubble": "Пузырь",
		"Bunker": "бункер",
		"Burrow": "ход",
		"Bush": "кустарник",
		"Butte": "холм",
		"Camp": "лагерь",
		"Canal": "канал",
		"Canopy": "навес",
		"Canvas": "холст",
		"Canyon": "каньон",
		"Cape": "плащ",
		"Center": "Центр",
		"Chaparral": "терновник",
		"Chasm": "разрыв",
		"Citadel": "оплот",
		"City": "город",
		"Clearing": "выруб",
		"Climax": "зенит",
		"Cloudland": "воздушный замок",
		"Coast": "берег",
		"Colony": "поселок",
		"Commune": "городок",
		"Confluence": "залив",
		"Continent": "континент",
		"Convention": "съезд",
		"Core": "костяк",
		"Cosmos": "космос",
		"Country": "край",
		"County": "округ",
		"Court": "суд",
		"Courtyard": "двор",
		"Cove": "свод",
		"Crater": "кратер",
		"Creek": "залив",
		"Crest": "гребень",
		"Crick": "спазм",
		"Crossing": "переход",
		"Crossroads": "перекресток",
		"Crown": "престол",
		"Dab": "мазок",
		"Dale": "Дейл",
		"Dam": "затон",
		"Daydream": "сон",
		"Defecation": "туалет",
		"Dell": "лес",
		"Delta": "исток",
		"Den": "притон",
		"Depths": "грот",
		"Desert": "Пустыня",
		"Dimension": "масштаб",
		"District": "приход",
		"Domain": "круг",
		"Dome": "купол",
		"Dream": "бред",
		"Dreamland": "огород",
		"Dreamworld": "розарий",
		"Dump": "склад",
		"Dune": "бархан",
		"Dungeon": "каземат",
		"Easement": "сарай",
		"Edge": "край",
		"Elevation": "подъем",
		"Empire": "престол",
		"Empyrean": "небосвод",
		"Enclosure": "кожух",
		"Entity": "объект",
		"Essence": "смысл",
		"Estate": "особняк",
		"Estuary": "горло",
		"Eternity": "век",
		"Ether": "эфир",
		"Everglade": "солончак",
		"Existence": "быт",
		"Expanse": "простор",
		"Exterior": "пейзаж",
		"Fable": "рассказ",
		"Fabrication": "вымысел",
		"Fantasia": "обман",
		"Farm": "хутор",
		"Field": "выкос",
		"Figment": "Призрак",
		"Firmament": "свод",
		"Fjord": "фьорд",
		"Flatland": "сарай",
		"Flats": "сквер",
		"Fold": "архив",
		"Foothold": "плацдарм",
		"Forest": "лес",
		"Forge": "горн",
		"Fortress": "город",
		"Foundation": "фонд",
		"Fountain": "фонтан",
		"Fraternity": "коллектив",
		"Front": "фронт",
		"Frontier": "кордон",
		"Galaxy": "цветник",
		"Garden": "сад",
		"Geyser": "Гейзер",
		"Glacier": "ледник",
		"Glade": "пролесок",
		"Globe": "глобус",
		"Grange": "амбар",
		"Grassland": "луг",
		"Graveyard": "Кладбище",
		"Grounds": "грунт",
		"Grove": "гай",
		"Gulf": "залив",
		"Gully": "сток",
		"Gutter": "слив",
		"Hamlet": "хутор",
		"Harbor": "порт",
		"Haven": "угол",
		"Heart": "Сердце",
		"Heaven": "рай",
		"Hedge": "забор",
		"Heights": "аул",
		"Hideout": "схрон",
		"Highland": "балкон",
		"Hill": "холм",
		"Hilltop": "пик",
		"Hinterland": "тыл",
		"Hive": "Блок улья",
		"Hole": "пролом",
		"Hollow": "кратер",
		"Homeland": "карьер",
		"Hoosegow": "карцер",
		"Hovel": "шалаш",
		"Hub": "очаг",
		"Illusion": "мираж",
		"Image": "образ",
		"Interior": "интерьер",
		"Island": "остров",
		"Isle": "клочок",
		"Islet": "островок",
		"Jungle": "притон",
		"Keystone": "камень",
		"Kingdom": "мир",
		"Knoll": "бугор",
		"Labyrinth": "лабиринт",
		"Lagoon": "лиман",
		"Lair": "загон",
		"Lake": "водоем",
		"Land": "Земля",
		"Legend": "сказ",
		"Limbo": "промежуток",
		"Locale": "брод",
		"Loch": "пролив",
		"Marsh": "марш",
		"Marshland": "бульвар",
		"Mass": "строй",
		"Maze": "лабиринт",
		"Meadow": "покос",
		"Meridian": "меридиан",
		"Mesa": "венец",
		"Midland": "континент",
		"Mine": "рудник",
		"Mirage": "мираж",
		"Mire": "ил",
		"Moorland": "валун",
		"Morass": "зыбун",
		"Mortuary": "морг",
		"Mound": "нанос",
		"Mountain": "пригорок",
		"Myth": "миф",
		"Nation": "народ",
		"Neighborhood": "квартал",
		"Nest": "рой",
		"Niche": "грот",
		"Nightmare": "кошмар",
		"Nirvana": "астрал",
		"Nursery": "инкубатор",
		"Oasis": "Оазис",
		"Object": "объект",
		"Ocean": "Океан",
		"OldTownRoad": "старый путь",
		"Orchard": "сад",
		"Origin": "исток",
		"Outback": "медвежий угол",
		"Outland": "отдаленный участок",
		"Outskirts": "пригород",
		"Overworld": "небесный мир",
		"Paintbrush": "Кисть",
		"Parable": "пересказ",
		"Paradise": "парадиз",
		"Park": "парк",
		"Passage": "пассаж",
		"Passing": "переход",
		"Pasture": "выпас",
		"Patch": "клочок",
		"Peak": "пик",
		"Pedestal": "пьедестал",
		"Peninsula": "полуостров",
		"Picture": "рисунок",
		"Pinnacle": "венец",
		"Pit": "колодец",
		"Place": "пункт",
		"Plains": "ветряк",
		"Planet": "мир",
		"Plateau": "плоский участок",
		"Plaza": "торговый центр",
		"Plot": "участок",
		"Plumbus": "плюмбус",
		"Point": "пункт",
		"Polestar": "путеводный свет",
		"Pond": "пруд",
		"Port": "порт",
		"Portrait": "портрет",
		"Pothole": "котел",
		"Prairie": "виадук",
		"Prison": "острог",
		"Province": "водоворот",
		"Pub": "паб",
		"Quagmire": "водопад",
		"Quarantine": "карантин",
		"Ranch": "вольер",
		"Rapids": "порог",
		"Ravine": "овраг",
		"Reach": "горизонт",
		"Reality": "вырез",
		"Realm": "грот",
		"Reef": "риф",
		"Refuge": "приют",
		"Region": "регион",
		"Remotes": "отшиб",
		"Residence": "дом",
		"Rest": "отель",
		"Retreat": "санаторий",
		"Ridge": "кряж",
		"Rift": "брод",
		"Ring": "ринг",
		"River": "поток",
		"Roost": "насест",
		"Root": "корень",
		"Route": "путь",
		"Run": "загон",
		"Sanctuary": "алтарь",
		"Savanna": "камин",
		"Schmeckle": "шмекль",
		"Scrubland": "кустарник",
		"Sea": "карцер",
		"Seaside": "курорт",
		"Section": "перегон",
		"Sector": "сектор",
		"Settlement": "выселок",
		"Shallows": "каскад",
		"Shanty": "барак",
		"Shantytown": "строительный городок",
		"Sheet": "саван",
		"Shire": "приход",
		"Shore": "короб",
		"Shrine": "мавзолей",
		"Shroud": "покров",
		"Shrubbery": "хворостняк",
		"Shrublands": "контейнер",
		"Site": "раскоп",
		"Slope": "склон",
		"Slumber": "легкий сон",
		"Snap": "захват",
		"Sod": "дерн",
		"Sorority": "девичник",
		"Source": "источник",
		"Space": "Космос",
		"Span": "пролет",
		"Sphere": "шар",
		"Spring": "лесок",
		"Square": "квадрат",
		"State": "штат",
		"Station": "вокзал",
		"Steppe": "корт",
		"Sticks": "посох",
		"Stonk": "огонь",
		"Story": "рассказ",
		"Strait": "пролив",
		"Stream": "поток",
		"Stretch": "галс",
		"Suburb": "пригород",
		"Summit": "верх",
		"Swale": "кряж",
		"Swamp": "заболоченный лес",
		"Sweep": "поворот",
		"Taiga": "таежный лес",
		"Tale": "сказ",
		"Temple": "храм",
		"Terrace": "газон",
		"Terrain": "рельеф",
		"Terraria": "террариум",
		"Terrarium": "террарий",
		"Territory": "район",
		"Thicket": "частокол",
		"Throne": "трон",
		"Tilt": "наклон",
		"Timberland": "подлесок",
		"Tip": "конец",
		"Tomb": "склеп",
		"Towel": "рушник",
		"Town": "город",
		"Tract": "тракт",
		"Trail": "след",
		"Trench": "котлован",
		"Tributary": "приток",
		"Tropic": "тропик",
		"Tundra": "тундровый лес",
		"Tunnel": "туннель",
		"Turf": "торф",
		"Underbelly": "теневой мир",
		"Undergrowth": "молодняк",
		"Underwood": "подрост",
		"Universe": "мир",
		"Unknown": "Неизвестный",
		"Upland": "суходол",
		"Utopia": "утопический мир",
		"Vale": "дол",
		"Valley": "раздол",
		"Vault": "подвал",
		"Veldt": "вельд",
		"Vicinity": "округ",
		"Vineyard": "виноградник",
		"Vision": "взгляд",
		"Void": "вакуум",
		"Ward": "приход",
		"Waste": "пустырь",
		"Wasteland": "клоповник",
		"Well": "резервуар",
		"Wetland": "болотный массив",
		"Wharf": "причал",
		"Wilderness": "заказник",
		"Wilds": "котлован",
		"Wildwood": "склеп",
		"Wonderland": "чудесный край",
		"Wood": "лес",
		"Woodland": "купол",
		"Woods": "курятник",
		"World": "мир",
		"Yard": "двор",
		"Yeet": "хламовник",
		"Zone": "пояс",
		"Latte": "Латте",
		"Vibe": "Инстинкт",
		"Passenger": "Пассажир",
		"Hernia": "Нарост",
		"Simp": "Простак",
		"Speedrun": "Турборежим",
		"Drip": "Слюнтяй",
		"Boingloings": "Болт",
		"Nooch": "Разрыхлитель",
		"Mood": "Настрой",
		"Chungus": "Толстяк",
		"Token": "Токен",
		"BathWater": "Душ",
		"NFT": "Биткоин",
		"Blockchain": "Блокчейн",
		"Crypto": "Капитал",
		"Virus": "Вирус",
		"DLC": "Майнинг",
		"Egg": "Плод",
		"Labor": "Труд",
		"Dollop": "Кусок",
		"Finger": "Палец",
		"Throat": "Нос",
		"Underwear": "Трикотаж",
		"Foot": "Фут",
		"Toilet": "Унитаз",
		"Tranch": "Взнос",
		"Cult": "Культ",
		"Mouth": "Рот",
		"Jalopy": "Драндулет",
		"Flapper": "Щиток",
		"Moon": "Месяц",
		"Sunrise": "Восход",
		"Sunset": "Закат",
		"Slice": "Ломоть",
		"Daybreak": "Рассвет",
		"End": "Конец",
		"Pearl": "Перл",
		"Tongue": "Язык",
		"Kiss": "Поцелуй",
		"Couch": "Одр",
		"Miasma": "Пар",
		"Fluid": "Раствор",
		"Triangle": "Треугольник",
		"Web": "Рулон",
		"Honey": "Мёд",
		"Leaf": "Лист",
		"Moss": "Мох",
		"Soil": "Грунт",
		"Dirt": "Ил",
		"Flower": "Цветок",
		"Eclipse": "Упадок",
		"Slime": "Слизень",
		"Delight": "Восторг",
		"Bane": "Яд",
		"Lie": "Обман",
		"Spiral": "Спуск",
		"Flex": "Шнур",
		"Chance": "Шанс",
		"Folly": "Каприз",
		"Regret": "Траур",
		"Fort": "Форт",
		"Door": "Дверь",
		"Head": "Котелок",
		"Study": "Курс",
		"Gaze": "Туман",
		"Magic": "Магик",
		"Lining": "Матрас",
		"Shoe": "Ботинок",
		"Sock": "Носок",
		"Croak": "Хрип",
		"Box": "Ящик",
		"Eye": "Глаз",
		"Sweater": "Свитер",
		"Snack": "Перекус",
		"Faith": "Выбор",
		"Hope": "Просвет",
		"Constant": "Итог",
		"Trap": "Капкан",
		"Treasure": "Клад",
		"Table": "Стол",
		"Mistake": "Промах",
		"Accident": "Случай",
		"Stick": "Кол",
		"Tree": "Прут",
		"Horizon": "Раздел",
		"Secretion": "Секрет",
		"Bundle": "Свёрток",
		"Heap": "Пакет",
		"Pile": "Ворох",
		"Boil": "Нарыв",
		"Excrement": "Помёт",
		"Excretion": "Взрыв",
		"Discharge": "Залп",
		"Infection": "Микроб",
		"Sack": "Мешок",
		"Harvest": "Урожай",
		"Legs": "Протез",
		"Disease": "Недуг",
		"Soup": "Суп",
		"Bowl": "Кубок",
		"Bowel": "Сосуд",
		"Bowels": "Потрох",
		"Nugget": "Самородок",
		"Carton": "Картон",
		"Eater": "Едок",
		"Wall": "Подъём",
		"Pie": "Диск",
		"Body": "Торс",
		"Salt": "Перец",
		"Tears": "Плач",
		"SaltMine": "Солерудник",
		"Sky": "Небосклон",
		"Torch": "Факел",
		"Grave": "Гроб",
		"Touch": "Щуп"
	},
    "nouns": {
		"Ability": "способности",
		"Absurdity": "нелепости",
		"Accidents": "происшествий",
		"Acne": "прыщей",
		"Acorns": "Желуди",
		"Adamantite": "адамантита",
		"Adoration": "обожания",
		"Adulthood": "зрелости",
		"Advantage": "преимущества",
		"Adventure": "приключения",
		"Agony": "агонии",
		"Alarm": "тревоги",
		"Alcohol": "алкоголя",
		"Ale": "Эль",
		"Allergies": "аллергий",
		"Amazement": "изумления",
		"Angels": "ангелов",
		"Anger": "гнева",
		"Anguish": "мучения",
		"AnimalCarcasses": "трупов животных",
		"Annoyance": "досады",
		"Anvils": "наковален",
		"Anxiety": "тревоги",
		"Apples": "яблок",
		"Apricots": "абрикосов",
		"Argon": "аргона",
		"Arrows": "стрел",
		"Arsenic": "мышьяка",
		"Arson": "поджога",
		"Arthritis": "артрита",
		"Asbestos": "асбеста",
		"Ash": "золы",
		"Assassins": "убийц",
		"Assault": "нападения",
		"Atrophy": "атрофии",
		"Awareness": "ознакомленности",
		"Awe": "трепета",
		"Bacon": "Бекон",
		"BadDecisions": "плохих решений",
		"BadJokes": "плохих шуток",
		"BadOmens": "плохих примет",
		"Balance": "равновесия",
		"Bamboo": "Бамбук",
		"Bananas": "бананов",
		"Bandits": "бандитов",
		"Bankruptcy": "банкротства",
		"Bark": "лая",
		"Bats": "летучих мышей",
		"Beauty": "красоты",
		"Beenades": "пчелонат",
		"Bees": "пчел",
		"Beggars": "попрошаек",
		"Beheadings": "обезглавливания",
		"Belief": "верования",
		"Betrayers": "предателей",
		"Birds": "птиц",
		"Birthdays": "дней рождений",
		"Bitterness": "горечи",
		"Bladders": "мочевых пузырей",
		"Blasphemy": "богохульства",
		"Blindness": "слепоты",
		"Blinkroot": "Мерцающий корень",
		"Blocks": "Блоки",
		"Blood": "крови",
		"Bloodletting": "кровопролития",
		"Bloodshed": "бойни",
		"Blossoms": "цветений",
		"Bone": "Кость",
		"Bones": "костей",
		"Boomers": "кенгуру",
		"Boots": "сапог",
		"Boredom": "скуки",
		"Boulders": "валунов",
		"Brains": "мозгов",
		"Branches": "веток",
		"Bravery": "смелости",
		"Bribery": "взятки",
		"Bridges": "мостов",
		"Brilliance": "великолепия",
		"BrokenBones": "сломанных костей",
		"BrokenDreams": "несбывшихся надежд",
		"BrokenGlass": "разбитого бокала",
		"Bronies": "пирожков",
		"Bubbles": "Пузырик",
		"Buckets": "ведер",
		"Bugs": "жуков",
		"Bums": "бродяг",
		"Bunnies": "кроликов",
		"Burglars": "воров",
		"BurningHair": "горящих волос",
		"BurntFlesh": "сгоревшей плоти",
		"BurntOfferings": "ритуальных жертв",
		"Butchery": "скотобойни",
		"Butterflies": "бабочек",
		"Cacti": "кактусов",
		"Calmness": "спокойствия",
		"Candy": "конфеты",
		"Care": "заботы",
		"Carnage": "резни",
		"Carrion": "падали",
		"Casualty": "увечья",
		"Cats": "котов",
		"Cattails": "рогозы",
		"Caves": "пещер",
		"Celebration": "Празднование",
		"Chainsaws": "цепных пил",
		"Chaos": "хаоса",
		"Charity": "благотворительности",
		"Cheats": "мошенников",
		"Cherries": "вишен",
		"Chests": "сундуков",
		"Childhood": "детства",
		"Children": "детей",
		"Chlorophyte": "хлорофита",
		"Cilantro": "кинзы",
		"Clarity": "чистоты",
		"Clay": "глины",
		"Clentamination": "очищения",
		"Cleverness": "ума",
		"Clouds": "облаков",
		"Cobalt": "Кобальт",
		"Coconuts": "кокосов",
		"Coffee": "кофе",
		"Coins": "Монеты",
		"Coldness": "холода",
		"Comfort": "удобства",
		"Compassion": "сочувствия",
		"Compost": "компоста",
		"Confidence": "доверия",
		"Confinement": "заключения",
		"Confusion": "запутанности",
		"Contentment": "удовлетворенности",
		"Convicts": "каторжников",
		"Copper": "Медь",
		"Corpses": "трупов",
		"Corruption": "порчи",
		"Courage": "храбрости",
		"Creation": "создания",
		"Creatures": "существ",
		"Creepers": "ползунов",
		"Crests": "гребней",
		"Crime": "преступления",
		"Criminals": "преступников",
		"Crimtane": "кримтана",
		"CripplingDepression": "сокрушительной депрессии",
		"Crooks": "крюков",
		"Crows": "ворон",
		"Crystals": "кристаллов",
		"Cthulhu": "Ктулху",
		"Curiosity": "любопытства",
		"CursedFlames": "Проклятый огонь",
		"Dabbing": "отделки",
		"Daisies": "маргариток",
		"DankMemes": "пробирающих до костей карикатур",
		"Darkness": "Тьма",
		"Darts": "дротиков",
		"Daughters": "дочерей",
		"Dawn": "рассвета",
		"Daybloom": "Цветок дня",
		"Deadbeats": "нищебродов",
		"DeadBodies": "мертвых тел",
		"Death": "смерти",
		"Deathweed": "Мертвая трава",
		"Debauchery": "распутства",
		"Debt": "долга",
		"Decapitation": "казни",
		"DecayingMeat": "загнивающего мяса",
		"Deceit": "уловки",
		"Deception": "жульничества",
		"Dedication": "посвящения",
		"Defeat": "поражения",
		"Defecation": "туалет",
		"Degradation": "ухудшения",
		"Delay": "задержки",
		"Delusion": "заблуждения",
		"Dementia": "маразма",
		"Demilogic": "полулогики",
		"Demonite": "демонита",
		"Demons": "демонов",
		"Derangement": "расстройства",
		"Despair": "отчаяния",
		"Desperation": "безрассудства",
		"Destruction": "разрушения",
		"DijonMustard": "дижонской горчицы",
		"Dirt": "грязи",
		"Disappointment": "разочарованности",
		"Disgust": "отвращения",
		"Dishonesty": "непорядочности",
		"Dismay": "смятения",
		"Distortion": "искажения",
		"Distribution": "распределения",
		"Divorce": "развода",
		"Doom": "фатума",
		"Dragonfruit": "патахайи",
		"Dragons": "драконов",
		"Dread": "ужаса",
		"Dreams": "мечтаний",
		"Drills": "тренировок",
		"Drums": "барабанов",
		"Ducks": "уток",
		"Dusk": "сумерек",
		"Dust": "пыли",
		"Duty": "долга",
		"Dysphoria": "подавленности",
		"Ears": "ушей",
		"Education": "обучения",
		"Eggs": "яиц",
		"Elderberries": "бузины",
		"Elegance": "элегантности",
		"Envy": "зависти",
		"Evasion": "бегства",
		"Evil": "Злой",
		"Exile": "изгнания",
		"Exploits": "подвигов",
		"Explosives": "Взрывчатка",
		"Extortion": "вымогательства",
		"Eyes": "глаз",
		"Fable": "рассказ",
		"FaceMonsters": "лицевых монстров",
		"Failures": "неудач",
		"Fairies": "фей",
		"Faith": "веры",
		"FallingStars": "падающих звезд",
		"Falsehood": "лживости",
		"FalseIdols": "лживых идолов",
		"FalseImprisonment": "обманного ареста",
		"Fame": "славы",
		"Famine": "голода",
		"Fantasy": "фантазии",
		"Fascination": "обаяния",
		"Fatality": "пагубности",
		"Fear": "страха",
		"Feathers": "перьев",
		"Feces": "осадка",
		"Felons": "уголовников",
		"Ferns": "папоротников",
		"Fiction": "выдумки",
		"Fiends": "злодеев",
		"Fingers": "пальцев",
		"Fireblossom": "Огнецвет",
		"Fireflies": "светлячков",
		"Fish": "Рыба",
		"Flails": "молотил",
		"Flatulence": "напыщенности",
		"Flatus": "дыхания",
		"Flesh": "плоти",
		"Floof": "пушистости",
		"Flowers": "цветов",
		"FlyingFish": "летучей рыбы",
		"FoodPoisoning": "пищевого отравления",
		"Forgery": "фальшивки",
		"Forks": "вилок",
		"Fraud": "обманщика",
		"Freaks": "причуд",
		"Freckles": "веснушек",
		"Freedom": "свободы",
		"Friendship": "дружбы",
		"Fright": "испуга",
		"Frogs": "лягушек",
		"Frost": "мороза",
		"Fruit": "Фрукт",
		"Gangsters": "бандитов",
		"Garbage": "мусора",
		"GarlicBread": "чесночного хлеба",
		"Gears": "шестерен",
		"Gel": "Гель",
		"Generation": "поколения",
		"GenXers": "поколения Х",
		"GenYers": "поколения Y",
		"Ghosts": "призраков",
		"Giggles": "смешков",
		"Gingers": "имбиря",
		"Girls": "девочек",
		"Glass": "Стекло",
		"Gloom": "мрака",
		"Gluttony": "обжорства",
		"Goals": "целей",
		"Goblins": "гоблинов",
		"Gold": "Золото",
		"Goldfish": "Золотая рыбка",
		"Gossip": "болтовни",
		"Grain": "зерна",
		"Grandfathers": "дедушек",
		"Grandmothers": "бабушек",
		"Granite": "Гранит",
		"Grapefruit": "Грейпфрут",
		"Grapes": "Виноград",
		"Grass": "травы",
		"Grasshoppers": "кузнечиков",
		"Graves": "могил",
		"Greed": "жадности",
		"Grief": "скорби",
		"Guitars": "гитар",
		"Guts": "кишок",
		"Hair": "волос",
		"Hamburgers": "гамбургеров",
		"Hammers": "молотков",
		"Hands": "рук",
		"Happiness": "счастья",
		"HappyEndings": "хеппи-эндов",
		"Hardship": "лишения",
		"Harpies": "гарпий",
		"Hate": "ненависти",
		"Hatred": "отвращения",
		"Heart": "Сердце",
		"Heartache": "душевной боли",
		"Hearts": "сердец",
		"Heels": "каблуков",
		"Hellstone": "Адский камень",
		"Herbs": "трав",
		"Heresy": "ереси",
		"Homicide": "убийства",
		"Honey": "Мед",
		"Hoodlums": "громил",
		"Hooks": "крюков",
		"Hooligans": "хулиганов",
		"Hopelessness": "обреченности",
		"Hornets": "шершней",
		"Horns": "рогов",
		"Hornswoggle": "одурачивания",
		"Horror": "ужаса",
		"Horrors": "ужасов",
		"Houses": "домов",
		"Humiliation": "унижения",
		"Hurt": "Раненый",
		"Hysteria": "истерии",
		"Ice": "льда",
		"Ichor": "Ихор",
		"Illness": "болезни",
		"Indictments": "обвинений",
		"Indigestion": "несварения",
		"Indignity": "пренебрежения",
		"Infancy": "младенчества",
		"Infections": "инфекций",
		"Inflammation": "воспаления",
		"Inflation": "вздутости",
		"Injury": "травмы",
		"Insanity": "безумия",
		"Insects": "насекомых",
		"Intelligence": "ума",
		"Intestines": "кишечника",
		"Invasions": "нападений",
		"Iron": "железа",
		"Irritation": "раздражения",
		"Isolation": "изоляции",
		"Ivy": "Плющ",
		"Jaws": "челюстей",
		"Jealousy": "ревности",
		"Jellyfish": "медузы",
		"Joy": "радости",
		"Justice": "правосудия",
		"Karens": "Карен",
		"Kidneys": "почек",
		"Kindness": "доброты",
		"Kittens": "котят",
		"Knives": "ножей",
		"Krypton": "криптона",
		"Lamps": "ламп",
		"Laughter": "смеха",
		"Lava": "лавы",
		"Lawsuits": "исков",
		"Lawyers": "адвокатов",
		"Lead": "свинца",
		"Leaves": "листьев",
		"Legend": "сказ",
		"Leggings": "леггинсов",
		"Legs": "ног",
		"Lemons": "лимонов",
		"Leprosy": "проказы",
		"Letdown": "упадка",
		"Lethargy": "летаргии",
		"Liberty": "свободы",
		"Lies": "лжи",
		"Life": "Жизнь",
		"LightningBugs": "светящихся жуков",
		"Lilies": "лилий",
		"Lilith": "Лилит",
		"Lips": "губ",
		"Litigation": "тяжбы",
		"Livers": "печени",
		"Loathing": "отвращения",
		"Lombago": "Ломбаго",
		"Loneliness": "одиночества",
		"Lore": "словесности",
		"Loss": "потери",
		"Love": "любви",
		"Luck": "удачи",
		"Luggage": "багажа",
		"Luminite": "Люминит",
		"Lungs": "легких",
		"Luxury": "роскоши",
		"Madness": "сумасшествия",
		"Maggots": "причуд",
		"Mana": "маны",
		"Mangos": "манго",
		"Mania": "мании",
		"Manslaughter": "человекоубийства",
		"Marble": "Мрамор",
		"Markets": "рынков",
		"Mastication": "пережевывания",
		"Maturity": "зрелости",
		"Medicine": "медицины",
		"Melancholy": "меланхолии",
		"Memes": "карикатур",
		"Mercy": "милосердия",
		"Meteorite": "Метеорит",
		"Mice": "мышей",
		"Midnight": "полночи",
		"MidnightRamen": "полночного рамена",
		"Millennials": "миллениалов",
		"Mimics": "мимиков",
		"Mirrors": "зеркал",
		"Misery": "мучения",
		"Misfortune": "невзгод",
		"MissingLimbs": "отсутствующих конечностей",
		"Models": "моделей",
		"Money": "денег",
		"Monotony": "однообразия",
		"Moonglow": "Лунное сияние",
		"Moonlight": "лунного света",
		"Morons": "идиотов",
		"Mortality": "смертности",
		"Moss": "мха",
		"Mourning": "Плакучий",
		"Mouths": "ртов",
		"Movement": "движения",
		"Muckers": "грубиянов",
		"Mud": "грязи",
		"Muggers": "болотных крокодилов",
		"Murder": "убийства",
		"Murderers": "убийц",
		"Mushrooms": "грибов",
		"Music": "Музыка",
		"Mystery": "тайны",
		"Myth": "миф",
		"Mythril": "мифрила",
		"Nausea": "тошноты",
		"Necromancers": "некромантов",
		"Necromancy": "некромантства",
		"Night": "Ночь",
		"Nightcrawlers": "ночных ползунов",
		"Nightmares": "кошмаров",
		"Nocram": "Нокрама",
		"NoRemorse": "отсутствия угрызений совести",
		"Nostalgia": "ностальгии",
		"Nudity": "обнаженности",
		"Obscurity": "темноты",
		"Obsidian": "Обсидиан",
		"Odor": "аромата",
		"OopsieDaisy": "чертовой ромашки",
		"Ooze": "тины",
		"OpenWounds": "открытых ран",
		"Opportunity": "возможности",
		"Options": "вариантов",
		"Oranges": "апельсинов",
		"Organs": "органов",
		"Orichalcum": "орихалка",
		"Outlaws": "беззаконников",
		"Owls": "сов",
		"PadThai": "Тайская еда",
		"Pain": "боли",
		"Palladium": "палладия",
		"Panhandlers": "попрошаек",
		"Panic": "паники",
		"Parasites": "паразитов",
		"Parties": "вечеринок",
		"PartyTime": "поры вечеринок",
		"Patience": "терпения",
		"Peace": "мира",
		"Penguins": "пингвинов",
		"Perjury": "вероломства",
		"Perspiration": "испарения",
		"Pickaxes": "кирок",
		"Pickpockets": "карманников",
		"Pineapples": "ананасов",
		"Pinky": "Пинки",
		"Piranha": "пираньи",
		"Piranhas": "пираний",
		"Pirates": "пиратов",
		"Pixies": "фей",
		"Plantero": "Плантеро",
		"Plants": "растений",
		"Platinum": "Платина",
		"Pleasure": "удовольствия",
		"Plums": "слив",
		"Politicians": "политиков",
		"Ponies": "пони",
		"Potions": "настоек",
		"Poverty": "бедности",
		"Power": "силы",
		"Pride": "гордости",
		"Prisms": "призм",
		"Privacy": "секретности",
		"Prophecy": "пророчества",
		"Psychology": "психологии",
		"PublicSpeaking": "публичных выступлений",
		"Puppies": "щеночков",
		"Rain": "Дождь",
		"Ramen": "рамена",
		"Rats": "крыс",
		"Reality": "вырез",
		"Regret": "сожаления",
		"Regurgitation": "отрыжки",
		"Relaxation": "расслабления",
		"Relief": "облегчения",
		"Remorse": "угрызений совести",
		"Repugnance": "отвращения",
		"Riches": "богатств",
		"RichMahogany": "Красная древесина",
		"Rocks": "скал",
		"Rope": "Веревка",
		"Roses": "роз",
		"RottenFruit": "гнилого фрукта",
		"RottingFlesh": "гниющей плоти",
		"Rumours": "слухов",
		"Sacrifice": "жертвоприношения",
		"Sacrilege": "кощунства",
		"Sadness": "печали",
		"Salesmen": "продавцов",
		"Sand": "песка",
		"Sandstone": "песчаной бури",
		"Sanity": "здравости",
		"Sap": "жизнеспособности",
		"Saplings": "растеньиц",
		"Sashimi": "Сашими",
		"Satisfaction": "удовольствия",
		"Scandal": "скандала",
		"Scorpions": "скорпионов",
		"Seasons": "сезонов",
		"Seaweed": "Водоросли",
		"Seclusion": "уединения",
		"Secrecy": "секретности",
		"Secrets": "секретов",
		"Seeds": "семечек",
		"SelfControl": "самоконтроля",
		"SelfDisgust": "самоотвращения",
		"SelfLoathing": "самоотторжения",
		"Services": "услуг",
		"SeveredHeads": "оторванных кистей",
		"Shade": "оттенка",
		"Shadows": "теней",
		"ShatteredHope": "разбитой надежды",
		"Shivers": "содроганий",
		"Shiverthorn": "Дрожецвет",
		"Shock": "удара",
		"Shrimp": "Креветка",
		"Silliness": "глупости",
		"Silt": "осадка",
		"Silver": "Серебро",
		"Sin": "греха",
		"Skeletons": "скелетов",
		"Skill": "умения",
		"Skin": "кожи",
		"Skulls": "черепов",
		"Sleep": "сна",
		"Slime": "Слизень",
		"Sloth": "ленивца",
		"Sloths": "ленивцев",
		"Smiles": "улыбок",
		"Smoke": "дыма",
		"Snails": "улиток",
		"Snatchers": "хватателей",
		"Snow": "Снежный биом",
		"Solicitation": "ходатайства",
		"Sorrow": "горя",
		"Spaghetti": "Спагетти",
		"Sparkles": "искр",
		"Spears": "копий",
		"Speed": "скорости",
		"SpicyRamen": "острого рамена",
		"Spikes": "шипов",
		"Spirits": "духов",
		"Splinters": "занозцев",
		"Sponges": "губок",
		"Sprinkles": "капель",
		"Spurs": "отростков",
		"Squid": "кальмара",
		"Squirrels": "белок",
		"StagnantWater": "стоячей воды",
		"Starfruit": "карамболы",
		"Starvation": "голодания",
		"Statues": "статуй",
		"Stone": "камня",
		"Stonks": "бомбежек",
		"Strength": "силы",
		"Strictness": "строгости",
		"Stumps": "обрубков",
		"Suffering": "страдания",
		"Sunflowers": "подсолнухов",
		"Superstition": "суеверия",
		"Surprise": "сюрприза",
		"Swagger": "бахвальства",
		"Swindlers": "мошенников",
		"Swords": "мечей",
		"Talent": "таланта",
		"TanSuits": "коричневых костюмов",
		"Taxes": "налогов",
		"TeddysBread": "хлеба Тэдди",
		"Teeth": "зубов",
		"Terror": "ужаса",
		"the Ancients": "древних",
		"the Angler": "рыбака",
		"the Apple": "яблока",
		"the Archer": "лучника",
		"the Aunt": "тети",
		"the Axe": "топора",
		"the Baby": "ребенка",
		"the Ball": "шара",
		"the Balloon": "воздушного шарика",
		"the Bat": "летучей мыши",
		"the Beast": "животного",
		"the Betrayed": "преданного",
		"the Blender": "смешивателя",
		"the Blood Moon": "кровавой луны",
		"the Bow": "лука",
		"the Bride": "невесты",
		"the Brony": "пирожка",
		"the Bubble": "пузыря",
		"the Bunny": "кролика",
		"the Cactus": "кактуса",
		"the Cloud": "облака",
		"the Coma": "комы",
		"the Corruptor": "разлагателя",
		"the Crab": "краба",
		"the Dance": "танца",
		"the Dark": "тьмы",
		"the Dead": "мертвого",
		"the Devourer": "пожирателя",
		"the Drax": "молотобура",
		"the Ducks": "уток",
		"the Eclipse": "затмения",
		"the Fairy": "феи",
		"the Father": "отца",
		"the Flu": "гриппа",
		"the Foot": "ноги",
		"the Frozen": "замороженного",
		"the Gift": "подарка",
		"the Ginger": "имбиря",
		"the Goblin": "гоблина",
		"the Golem": "голема",
		"the GreatestGeneration": "величайшего поколения",
		"the Groom": "жениха",
		"the Guest": "гостя",
		"the Hammer": "молотка",
		"the Hammush": "грибомолота",
		"the Head": "головы",
		"the Heavens": "небес",
		"the Hipster": "модника",
		"the Hobo": "бродяжки",
		"the Homeless": "бездомного",
		"the King": "короля",
		"the Law": "закона",
		"the Library": "библиотеки",
		"the Lihzahrd": "ящщера",
		"the Lilith": "лилит",
		"the Lizard King": "короля-ящера",
		"the LostGeneration": "потерянного поколения",
		"the Mirror": "зеркала",
		"the Monster": "чудовища",
		"the Moon": "луны",
		"the Mother": "матери",
		"the Mummy": "мумии",
		"the Mushroom": "гриба",
		"the Narc": "наркомана",
		"the Needy": "неимущего",
		"the Nude": "обнаженного",
		"the Old One": "старика",
		"the Pandemic": "пандемии",
		"the Pickaxe": "кирки",
		"the Picksaw": "киркопила",
		"the Pigron": "свинодракона",
		"the Po Boy": "бутерброд с креветкой",
		"the Porcelain God": "фарфорового бога",
		"the Prism": "призмы",
		"the Prophecy": "пророчества",
		"the Pwnhammer": "святого молота",
		"the Queen": "королевы",
		"the Ramen": "рамена",
		"the Right": "права",
		"the Scholar": "ученика",
		"the Shark": "акулы",
		"the Sickle": "косы",
		"the Sky": "неба",
		"the Snap": "хватки",
		"the Snitch": "ябеды",
		"the Spelunker": "спелеолога",
		"the Staff": "посоха",
		"the Stars": "звезд",
		"the Stench": "смрада",
		"the Stooge": "прихлебателя",
		"the Sun": "солнца",
		"the Sword": "меча",
		"the Tooth": "зуба",
		"the Tortoise": "черепахи",
		"the Tree": "дерева",
		"the Trend": "тенденции",
		"the Undead": "зомби",
		"the Unicorn": "единорога",
		"the Union": "союза",
		"the Unknown": "неизвестного",
		"the Varmint": "хищника",
		"the Waraxe": "Варакса",
		"the Yoyo": "йо-йо",
		"Thieves": "воров",
		"Thorns": "Шипы",
		"Thunder": "грома",
		"Tin": "олова",
		"Tingling": "покалывания",
		"Tiredness": "измученности",
		"Titanium": "титана",
		"Tombstones": "надгробных плит",
		"Torches": "факелов",
		"Torment": "муки",
		"TornMuscles": "разорванных мышц",
		"Torture": "пытки",
		"Traitors": "изменников",
		"Tramps": "босяков",
		"Tranquility": "спокойствия",
		"Traps": "ловушек",
		"Trash": "отбросов",
		"Treasure": "сокровища",
		"Trees": "деревьев",
		"Trends": "тенденций",
		"Trouble": "беспокойства",
		"Truffles": "трюфелей",
		"Trunks": "стволов",
		"Trust": "доверия",
		"Tungsten": "вольфрама",
		"Twigs": "веточек",
		"Twilight": "сумерек",
		"TwistedAnkles": "вывихнутых лодыжек",
		"Umbrellas": "зонтов",
		"UnjustPrices": "несправедливых цен",
		"Upchuck": "тошноты",
		"Vagabonds": "скитальцев",
		"Vampires": "вампиров",
		"Vanity": "Украшения",
		"Venom": "яда",
		"Victims": "жертв",
		"Victory": "победы",
		"Villains": "злодеев",
		"Vines": "лоз",
		"Violets": "фиалок",
		"Vomit": "рвоты",
		"Vultures": "стервятников",
		"Wands": "прутьев",
		"Wariness": "осторожности",
		"Warmth": "Согревание",
		"Wasps": "ос",
		"Waterleaf": "Воднолист",
		"Weakness": "слабости",
		"Wealth": "богатства",
		"Webs": "сетей",
		"Weeds": "трав",
		"Werewolves": "оборотней",
		"Whoopsies": "какашек",
		"Wings": "крыльев",
		"Wires": "проводов",
		"Wisdom": "мудрости",
		"Woe": "горя",
		"Wood": "лес",
		"Worms": "червей",
		"Worries": "тревог",
		"Wrath": "Месть",
		"Wrenches": "гаечных ключей",
		"Wyverns": "виверн",
		"Xenon": "ксенона",
		"Yoyos": "йо-йо",
		"Zombies": "зомби",
		"Zoomers": "зумеров",
		"AngryGamers": "Злые геймеры",
		"BadLuck": "Невезение",
		"The Torch God": "Бог факелов",
		"Bodies": "Мертвецов",
		"Lilypads": "Кувшинок",
		"Merica": "Материка",
		"FOMO": "Выгоды",
		"Boom-Boom": "Грохота",
		"Facts": "Фактов",
		"DiamondHands": "Алмазов",
		"Griefers": "Вредителей",
		"Loot": "Добычи",
		"Microtransactions": "Кредита",
		"Sounds": "Звуков",
		"Sauce": "Соуса",
		"theBunghole": "Пролома",
		"StinkBugs": "Щитников",
		"MomsSpaghetti": "Риса",
		"theFellowKids": "Приятелей",
		"MadCowDisease": "Ящура",
		"ImposterSyndrome": "Синдрома",
		"theDemogorgon": "Демогоргона",
		"FlyingSaucers": "Самовара",
		"theSpirits": "Духов",
		"Sassages": "Сервелата",
		"Dillweeds": "Укропа",
		"DingDongs": "Гонга",
		"Trypophobia": "Трипофобии",
		"Taxation": "Налогов",
		"DirtBlocks": "Блоков",
		"Mucus": "Лишайника",
		"Sewage": "Стоков",
		"theWorld": "Миров",
		"Man": "Человека",
		"Mankind": "Человечества",
		"BadTimes": "Кризиса",
		"GoodTimes": "Расцвета",
		"Winning": "Выигрыша",
		"Winners": "Чемпионов",
		"Losers": "Неудачников",
		"BraggingRights": "Гонора",
		"ItemDuping": "Повтора",
		"Hoiks": "Подкопа",
		"Purity": "Порядка",
		"Larceny": "Угона",
		"theWise": "Мудреца",
		"theFool": "Дурака",
		"BoneSpurs": "Мозоля",
		"theElderly": "Старейшины",
		"Wolves": "Волка",
		"Hope": "Залива",
		"Concern": "Интереса",
		"Teamwork": "Коллектива",
		"SnakeOil": "Удава",
		"Snakes": "Змеёнышей",
		"Shenanigans": "Выкрутасов",
		"Foam": "Пенопласта",
		"Pus": "Гноя",
		"theGoat": "Козла",
		"MemeLords": "Мемлорда",
		"OverConfidence": "Авторитета",
		"theMerchant": "Купца",
		"theZoologist": "Зоолога",
		"Wizards": "Мага",
		"Partying": "Банкета",
		"thePrincess": "Принцессы",
		"BadAdvice": "Подвоха",
		"BadTiming": "Времени",
		"BrokenPromises": "Надежд",
		"GoodAdvice": "Совета",
		"Balloons": "Баллонов",
		"Ruination": "Краха",
		"Legends": "Мифов",
		"Humanity": "Народа",
		"Time": "Хронометра",
		"Screams": "Воя",
		"Burnination": "Сожжения",
		"Thinking": "Разума",
		"Change": "Скачка",
		"Listening": "Послушания",
		"Learning": "Уроков",
		"Forgiveness": "Покоя",
		"Redemption": "Выкупа",
		"Understanding": "Рассудка",
		"Stress": "Стресса",
		"Sunshine": "Света",
		"Fortitude": "Стойкости",
		"Milk": "Молока",
		"Pizza": "Пиццы",
		"Cyborgs": "Киборгов",
		"Dogs": "Собак",
		"Worlds": "Вселенной",
		"Ogres": "Огров",
		"Promises": "Обещаний",
		"theManager": "Босса",
		"Cenx": "Ценкса",
		"Souls": "Душ",
		"Wonder": "Чуда",
		"Marvel": "Диковин",
		"Miracles": "Чудес",
		"theProdigy": "Дарования",
		"Melodies": "Мелодий",
		"Lyrics": "Стихов",
		"Songs": "Песен",
		"Harmony": "Гармонии",
		"Peril": "Риска",
		"Voilence": "Погрома",
		"Gemcorns": "Изумрудов",
		"Rainbows": "Радуги",
		"Buttercups": "Лютиков",
		"Orchids": "Орхидей",
		"Tulips": "Тюльпанов",
		"Pansies": "Пионов"
	},
	"special": {
		"TheConstant": "Константа"
	},
};